name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pytest flake8
    - name: Lint
      working-directory: ./backend
      run: flake8 app --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Test
      working-directory: ./backend
      run: pytest tests/ || echo "No tests yet"

  frontend-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install and build
      working-directory: ./frontend
      run: |
        npm ci
        npm run build

  deploy-aws:
    needs: [backend-test, frontend-test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Build and push backend to ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        cd backend
        docker build -t $ECR_REGISTRY/bank-analyzer-backend:$IMAGE_TAG .
        docker tag $ECR_REGISTRY/bank-analyzer-backend:$IMAGE_TAG $ECR_REGISTRY/bank-analyzer-backend:latest
        docker push $ECR_REGISTRY/bank-analyzer-backend:$IMAGE_TAG
        docker push $ECR_REGISTRY/bank-analyzer-backend:latest
    
    - name: Build and push frontend to ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        cd frontend
        docker build -t $ECR_REGISTRY/bank-analyzer-frontend:$IMAGE_TAG .
        docker tag $ECR_REGISTRY/bank-analyzer-frontend:$IMAGE_TAG $ECR_REGISTRY/bank-analyzer-frontend:latest
        docker push $ECR_REGISTRY/bank-analyzer-frontend:$IMAGE_TAG
        docker push $ECR_REGISTRY/bank-analyzer-frontend:latest
